name: Release

on:
  pull_request: {}
  push:
    tags:
        - 'v*.*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/toltec-dev/qt
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          ./dist.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
